### ISSUE TITLE
urldefense v3: new encoding

### ISSUE THREAD

**Issue by cardi** [cardi/proofpoint-url-decoder#4]
Example URL: `https://urldefense[.]com/v3/__https://contact.framasoft.org/*newsletter__;Iw!!LIr3w8kk_Xxm!6BNqFLJ13q7N5_lf3XQFlmTtgY5CkKjhfcIn4ybAhA1_gx_y07jmQ4uvR2QZ$`

**Comment by rstory** [comment]
looks to me like you just need to extract what's between the double underscore pairs.. this works for me as a shell script:

` echo "$url" | sed -e 's/.*__\(.*\)__;.*/\1/'`

**Comment by cardi** [comment]
Thanks, @rstory. 

I think there is some additional decoding in the extracted URL, for example I think `*` decodes to `_`? There are probably some other mappings (`!`?) I'm not thinking of.

And it looks like some of the other parameters have been moved. Looks like `!!` and `!` might be delimeters and then they've done some other encoding or aggregation on the rest.
